const $=id=>document.getElementById(id);
const B=[{id:'lumen',name:'LUMEN WRAITH',title:'O Farol Sem Voz',bpm:108,hp:1000,c:'#55e9ff',d:1},{id:'morrow',name:'MORROW VELVET',title:'A Cantora da Fenda',bpm:124,hp:1200,c:'#ff4b9a',d:2},{id:'iron',name:'IRON CHOIR',title:'O Coro Mecânico',bpm:138,hp:1400,c:'#ffbd65',d:3},{id:'nyx',name:'NYX PETAL',title:'A Flor dos Ecos',bpm:118,hp:1550,c:'#b984ff',d:4},{id:'cinder',name:'CINDER KING',title:'Rei das Brasas Frias',bpm:148,hp:1750,c:'#ff664d',d:5},{id:'echo',name:'THE LAST ECHO',title:'Seu Outro Lado',bpm:156,hp:2100,c:'#d6ff66',d:6}];
let save=JSON.parse(localStorage.rsreborn||'{"unlocked":["lumen"],"best":{}}');let boss=B[0],rhythm=null,soul=null,audioCtx=null,gain=null,screen='menu';
const show=s=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('screen-'+s).classList.add('active');screen=s};
function audio(){if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();gain=audioCtx.createGain();gain.gain.value=(+$('volume').value||70)/100;gain.connect(audioCtx.destination)}audioCtx.resume()}
function beep(f=440,d=.08){if(!audioCtx)return;let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;g.gain.value=.04;g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.connect(g).connect(gain);o.start();o.stop(audioCtx.currentTime+d)}
function saveIt(){localStorage.rsreborn=JSON.stringify(save)}
function drawBosses(){let g=$('bossGrid');g.innerHTML='';B.forEach((b,i)=>{let ok=save.unlocked.includes(b.id),x=document.createElement('button');x.className='bossCard '+(ok?'':'locked')+(boss===b?' selected':'');x.disabled=!ok;x.innerHTML=`<em>${save.best[b.id]||'—'}</em><small>00${i+1}</small><strong>${b.name}</strong><small>${b.title}</small>`;x.onclick=()=>{boss=b;drawBosses();info()};g.append(x)});info()}
function info(){let b=boss;$('bossInfo').innerHTML=`<p class="eyebrow">BOSS ${String(B.indexOf(b)+1).padStart(2,'0')}</p><h3>${b.name}</h3><p>${b.title}</p><p>DIFFICULDADE: ${'★'.repeat(b.d)}<br>MÚSICA: ${b.bpm} BPM<br>MELHOR: ${save.best[b.id]||'—'}</p><button class="launch" id="launch">ENFRENTAR BOSS</button>`;$('launch').onclick=()=>startRhythm()}
function startRhythm(){audio();show('rhythm');$('rhythmBoss').textContent=boss.name;$('rhythmTitle').textContent=boss.name;document.querySelectorAll('.note').forEach(n=>n.remove());rhythm=new Rhythm(boss);rhythm.go()}
class Rhythm{constructor(b){this.b=b;this.notes=[];this.running=true;this.score=0;this.combo=0;this.max=0;this.hit=0;this.miss=0;this.start=0;this.window=[80,130,200][+$('hitWindow').value];let p=[0,1,2,3,2,1,0,3],beat=60000/b.bpm;for(let i=0;i<48;i++)this.notes.push({t:2200+i*beat/2,l:p[(i+b.d)%p.length],hit:false,e:null})}
go(){$('ready').textContent='3';setTimeout(()=>{$('ready').textContent='2'},500);setTimeout(()=>{$('ready').textContent='1'},1000);setTimeout(()=>{if(this.running){$('ready').textContent='GO!';this.start=performance.now();this.loop()}},1500)}
loop=()=>{if(!this.running)return;let t=performance.now()-this.start;for(let n of this.notes){if(n.hit)continue;if(!n.e){n.e=document.createElement('div');n.e.className='note';n.e.textContent=['←','↓','↑','→'][n.l];$('lanes').children[n.l].append(n.e)}n.e.style.top=(70+(n.t-t)/1000*360)+'px';if(t>n.t+this.window+100){n.hit=true;n.e.remove();this.combo=0;this.miss++;judge('MISS')}}$('score').textContent=String(this.score).padStart(6,'0');if(t>this.notes[this.notes.length-1].t+700){this.running=false;document.querySelectorAll('.note').forEach(n=>n.remove());setTimeout(()=>startSoul(this),700);return}requestAnimationFrame(this.loop)};
key=k=>{if(!this.running)return;let l={d:0,f:1,j:2,k:3,arrowleft:0,arrowdown:1,arrowup:2,arrowright:3}[k];if(l==null)return;let t=performance.now()-this.start,n=this.notes.find(n=>!n.hit&&n.l===l);if(!n)return;let q=Math.abs(t-n.t);if(q<=this.window){n.hit=true;n.e?.remove();let z=q<=40?'PERFECT':q<=90?'GREAT':'GOOD';this.combo++;this.max=Math.max(this.max,this.combo);this.hit++;this.score+=(z==='PERFECT'?300:z==='GREAT'?200:100)+this.combo*5;judge(z);beep(330+l*90)}else if(t>n.t-this.window){n.hit=true;n.e?.remove();this.combo=0;this.miss++;judge('MISS')}}}
function judge(x){$('judgement').textContent=x;$('combo').textContent='COMBO '+rhythm.combo}
function startSoul(r){show('soul');$('soulBoss').textContent=boss.name;$('soulScore').textContent=String(r.score).padStart(6,'0');soul=new Soul(r);soul.go()}
class Soul{constructor(r){this.r=r;this.c=$('arena');this.x=450;this.y=400;this.hp=100;this.bhp=Math.max(1,boss.hp-r.score*.25);this.max=this.bhp;this.p=[];this.t=0;this.last=performance.now();this.run=true;this.keys={};this.down=e=>{this.keys[e.key.toLowerCase()]=1};this.up=e=>delete this.keys[e.key.toLowerCase()]}
go(){addEventListener('keydown',this.down);addEventListener('keyup',this.up);this.loop()}
loop=()=>{if(!this.run)return;let n=performance.now(),dt=Math.min(.03,(n-this.last)/1000);this.last=n;this.t+=dt;let dx=(this.keys.d||this.keys.arrowright?1:0)-(this.keys.a||this.keys.arrowleft?1:0),dy=(this.keys.s||this.keys.arrowdown?1:0)-(this.keys.w||this.keys.arrowup?1:0),l=Math.hypot(dx,dy)||1;this.x=Math.max(30,Math.min(870,this.x+dx/l*260*dt));this.y=Math.max(40,Math.min(480,this.y+dy/l*260*dt));if(Math.floor(this.t*4)!==Math.floor((this.t-dt)*4))this.spawn();for(let p of this.p){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(Math.hypot(p.x-this.x,p.y-this.y)<p.r+8){this.hp-=8;p.life=0}}this.p=this.p.filter(p=>p.life>0);this.bhp-=5*dt;if(this.hp<=0)return this.end(false);if(this.bhp<=0)return this.end(true);this.draw();requestAnimationFrame(this.loop)}
spawn(){let a=Math.random()*Math.PI*2,s=100+boss.d*20;this.p.push({x:450,y:250,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:7,life:6})}
draw(){let c=this.c.getContext('2d');c.clearRect(0,0,900,520);c.fillStyle='#080511';c.fillRect(0,0,900,520);c.strokeStyle='#39284d';c.strokeRect(20,30,860,460);c.fillStyle=boss.c;c.beginPath();c.arc(450,120,38,0,7);c.fill();for(let p of this.p){c.fillStyle=boss.c;c.beginPath();c.arc(p.x,p.y,p.r,0,7);c.fill()}c.fillStyle='#fff';c.beginPath();c.arc(this.x,this.y,9,0,7);c.fill();$('playerHp').style.width=this.hp+'%';$('bossHp').style.width=(this.bhp/this.max*100)+'%';$('bossHpText').textContent=boss.name+' '+Math.ceil(this.bhp)+' HP'}
end(win){this.run=false;removeEventListener('keydown',this.down);removeEventListener('keyup',this.up);let score=win?Math.round(this.r.score+this.hp*10):Math.floor(this.r.score*.4);if(win){let i=B.indexOf(boss);if(B[i+1]&&!save.unlocked.includes(B[i+1].id))save.unlocked.push(B[i+1].id)}save.best[boss.id]=Math.max(save.best[boss.id]||0,score);saveIt();$('resultEyebrow').textContent=win?'BOSS CLEARED':'SOUL SHATTERED';$('resultTitle').textContent=win?'VICTORY':'TRY AGAIN';$('resultRank').textContent=win?'S':'C';$('resultStats').textContent=`SCORE ${score} · COMBO ${this.r.max} · HITS ${this.r.hit} · MISSES ${this.r.miss}`;show('result')}}

document.querySelectorAll('[data-menu]').forEach(b=>b.onclick=()=>show('menu'));$('play').onclick=()=>startRhythm();$('bossSelect').onclick=()=>{drawBosses();show('boss')};$('practice').onclick=()=>{drawBosses();show('boss')};$('settings').onclick=()=>show('settings');$('volume').oninput=e=>{$('volOut').textContent=e.target.value+'%';if(gain)gain.gain.value=e.target.value/100};$('hitWindow').oninput=e=>$('windowOut').textContent=['TIGHT','NORMAL','LOOSE'][+e.target.value];$('reset').onclick=()=>{localStorage.removeItem('rsreborn');location.reload()};$('quitRhythm').onclick=()=>{if(rhythm)rhythm.running=false;show('menu')};$('quitSoul').onclick=()=>{if(soul)soul.run=false;show('menu')};$('retry').onclick=()=>startRhythm();addEventListener('keydown',e=>{if(screen==='rhythm')rhythm?.key(e.key.toLowerCase())});drawBosses();show('menu');